# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: macOS-latest

steps:
- script: dotnet restore build/Build.Microsoft.Maui.Graphics.Mac.sln
  displayName: 'NuGet Restore'

- script: |
    msbuild build/Build.Microsoft.Maui.Graphics.Mac.sln /verbosity:normal /t:Rebuild /p:Configuration=Release
  displayName: 'Build'
