trigger:
  branches:
    include:
    - main
  tags:
    include:
    - '*'
  paths:
    include:
    - '*'
    exclude:
    - .github/*
    - docs/*
    - CODE-OF-CONDUCT.md
    - CONTRIBUTING.md
    - LICENSE.TXT
    - PATENTS.TXT
    - README.md
    - SECURITY.md
    - THIRD-PARTY-NOTICES.TXT

pr:
  branches:
    include:
    - main
  paths:
    include:
    - '*'
    exclude:
    - .github/*
    - docs/*
    - CODE-OF-CONDUCT.md
    - CONTRIBUTING.md
    - LICENSE.TXT
    - PATENTS.TXT
    - README.md
    - SECURITY.md
    - THIRD-PARTY-NOTICES.TXT

pool:
  vmImage: windows-latest

steps:
- script: dotnet restore build/Build.Microsoft.Maui.Graphics.Mac.sln
  displayName: 'NuGet Restore'

- task: MSBuild@1
  displayName: 'Build Legacy'
  inputs:
    solution: build/Build.Microsoft.Maui.Graphics.Windows.sln
    configuration: Release
    restoreNugetPackages: true
    msbuildArguments: /verbosity:normal /t:Build
 
- task: DotNetCoreCLI@2
  displayName: 'Build NET6'
  inputs:
    command: 'build'
    projects: build/Build.Microsoft.Maui.Graphics-net6.sln
    arguments: -p:Configuration=Release

- task: NuGetCommand@2
  inputs:
    command: 'pack'
    packagesToPack: 'build/JonLipsky.Microsoft.Maui.Graphics.nuspec'
    packDestination: '$(Build.ArtifactStagingDirectory)'
    versioningScheme : 'byEnvVar'
    versionEnvVar: 'NugetVersion'

- task: PublishBuildArtifacts@1
  condition: always()
  displayName: publish artifacts
  inputs:
    ArtifactName: nuget