trigger:
- main

pool:
  vmImage: macOS-latest

steps:
- script: dotnet restore build/Build.Microsoft.Maui.Graphics.Mac.sln
  displayName: 'NuGet Restore'

- script: |
    msbuild build/Build.Microsoft.Maui.Graphics.Mac.sln /verbosity:normal /t:Rebuild /p:Configuration=Release
  displayName: 'Build'

- task: NuGetCommand@2
  inputs:
    command: 'pack'
    packagesToPack: 'build/JonLipsky.Microsoft.Maui.Graphics.nuspec'
    packDestination: '$(Build.ArtifactStagingDirectory)'
    versioningScheme : 'byEnvVar'
    versionEnvVar: 'NugetVersion'

- task: PublishBuildArtifacts@1
  condition: always()
  displayName: publish artifacts
  inputs:
    ArtifactName: nuget