variables:
- name: BuildVersion
  value: $[counter('release-counter', 1)]

trigger:
  branches:
    include:
    - main
  tags:
    include:
    - '*'
  paths:
    include:
    - '*'
    exclude:
    - .github/*
    - docs/*
    - CODE-OF-CONDUCT.md
    - CONTRIBUTING.md
    - LICENSE.TXT
    - PATENTS.TXT
    - README.md
    - SECURITY.md
    - THIRD-PARTY-NOTICES.TXT

pr:
  branches:
    include:
    - main
  paths:
    include:
    - '*'
    exclude:
    - .github/*
    - docs/*
    - CODE-OF-CONDUCT.md
    - CONTRIBUTING.md
    - LICENSE.TXT
    - PATENTS.TXT
    - README.md
    - SECURITY.md
    - THIRD-PARTY-NOTICES.TXT

pool:
  vmImage: windows-latest

steps:

- task: NuGetToolInstaller@1
  displayName: 'Use NuGet 5.7.0'
  inputs:
    versionSpec: 5.7.0

- task: DotNetCoreCLI@2
  displayName: 'Install NET6'
  inputs:
    command: 'build'
    projects: |
      src\external\DotNet\DotNet.csproj 

- task: NuGetCommand@2
  displayName: 'Restore sln'
  inputs:
    command: 'restore'
    restoreSolution: build\Build.Microsoft.Maui.Graphics.Windows.sln

- task: MSBuild@1
  displayName: 'Build Graphics with MSBUILD'
  inputs:
    solution: build\Build.Microsoft.Maui.Graphics.Windows.sln
    configuration: Release
    msbuildArguments: /verbosity:normal /t:Build

- script: src\bin\dotnet\dotnet build build\Build.Microsoft.Maui.Graphics-net6.sln -p:Configuration=Release
  displayName: 'Build Graphics with NET6'

- task: NuGetCommand@2
  displayName: 'Pack nupkg'
  inputs:
    command: 'pack'
    packagesToPack: 'build/Microsoft.Maui.Graphics.nuspec'
    packDestination: '$(Build.ArtifactStagingDirectory)'
    basePath: '$(System.DefaultWorkingDirectory)'
    versioningScheme : 'byEnvVar'
    versionEnvVar: 'BUILD_BUILDNUMBER'

- task: PublishBuildArtifacts@1
  condition: always()
  displayName: publish artifacts
  inputs:
    ArtifactName: nuget