name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - name: Checkout source code
      uses: actions/checkout@v2
              
    - name: Restore dependencies
      run: dotnet restore System.Graphics.Mac.sln
    
    - name: Build
      run: msbuild System.Graphics.Mac.sln /verbosity:normal /t:Rebuild /p:Configuration=Release
    
