name: Build and Release to GitHub Packages

env:
  DotNetVersion: 6.0.100-preview.2.21155.3
  AndroidMsi: https://dl.internalx.com/vsts-devdiv/Xamarin.Android/public/net6/4534967/main/f4d8fe238b15eadfc7842749bf13e5fca3e2f2d2/Microsoft.NET.Workload.Android.11.0.200.148.msi
  AndroidPkg: https://dl.internalx.com/vsts-devdiv/Xamarin.Android/public/net6/4534967/main/f4d8fe238b15eadfc7842749bf13e5fca3e2f2d2/Microsoft.NET.Workload.Android-11.0.200-ci.f4d8fe238b15eadfc7842749bf13e5fca3e2f2d2.148.pkg
  iOSMsi: https://bosstoragemirror.azureedge.net/wrench/main/98c8649d0c7d1e3c4c8d8d09e022befa853fb1e7/4541181/package/Microsoft.NET.Workload.iOS.14.4.100-ci.main.1192.msi
  iOSPkg: https://bosstoragemirror.azureedge.net/wrench/main/98c8649d0c7d1e3c4c8d8d09e022befa853fb1e7/4541181/package/notarized/Microsoft.iOS.Bundle.14.4.100-ci.main.1192.pkg
  MacCatalystPkg: https://bosstoragemirror.azureedge.net/wrench/main/98c8649d0c7d1e3c4c8d8d09e022befa853fb1e7/4541181/package/notarized/Microsoft.MacCatalyst.Bundle.14.3.100-ci.main.337.pkg

on:
  push:
    branches: [ release/github-packages ]

jobs:
  build-on-windows:
    runs-on: windows-latest
    steps:

    - name: Checkout source code
      uses: actions/checkout@v2

    - name: Install DotNet Preview
        shell: pwsh
        run: |
          $ProgressPreference = 'SilentlyContinue'
          Invoke-WebRequest -Uri "https://dot.net/v1/dotnet-install.ps1" -OutFile dotnet-install.ps1
          & .\dotnet-install.ps1 -Version $env:DotNetVersion -InstallDir "$env:ProgramFiles\dotnet\" -Verbose
          & dotnet --list-sdks
          & dotnet tool install --global boots --add-source "https://api.nuget.org/v3/index.json"
          & boots $env:AndroidMsi
          & boots $env:iOSMsi

    - name: Install NuGet
      uses: nuget/setup-nuget@v1
      with:
        nuget-version: '5.x'

    - name: NuGet Restore
      run: |
        nuget restore build/Build.Microsoft.Maui.Graphics.Windows.sln
        dotnet restore build/Build.Microsoft.Maui.Graphics-net6.sln

    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1.0.2

#    - name: Update project version
#      uses: roryprimrose/set-vs-sdk-project-version@v1
#      with:
#        projectFilter: 'src/*/*.csproj'
#        version: '0.1.${{ github.run_number }}'   
        
    - name: Build
      run: |
        msbuild build/Build.Microsoft.Maui.Graphics.Windows.sln /verbosity:normal /t:Rebuild /p:Configuration=Release
        dotnet build build/Build.Microsoft.Maui.Graphics-net6.sln -p:Configuration=Release

    #- name: NuGet Pack
    #  run: nuget pack build/JonLipsky.Microsoft.Maui.Graphics.GDI.Winforms.nuspec -Version 0.1.${{ github.run_number }} -OutputDirectory . -BasePath .

    #- name: NuGet Pack
    #  run: nuget pack build/JonLipsky.Microsoft.Maui.Graphics.SharpDX.UWP.nuspec -Version 0.1.${{ github.run_number }} -OutputDirectory . -BasePath .

    #- name: NuGet Pack
    #  run: nuget pack build/JonLipsky.Microsoft.Maui.Graphics.SharpDX.UWP.nuspec -Version 0.1.${{ github.run_number }} -OutputDirectory . -BasePath .

    #- name: NuGet Pack
    #  run: nuget pack build/JonLipsky.Microsoft.Maui.Graphics.Skia.WPF.nuspec -Version 0.1.${{ github.run_number }} -OutputDirectory . -BasePath .

    #- name: NuGet Pack
    #  run: nuget pack build/JonLipsky.Microsoft.Maui.Graphics.Text.WPF.nuspec -Version 0.1.${{ github.run_number }} -OutputDirectory . -BasePath .

    #- name: NuGet Pack
    #  run: nuget pack build/JonLipsky.Microsoft.Maui.Graphics.Win2D.UWP.nuspec -Version 0.1.${{ github.run_number }} -OutputDirectory . -BasePath .

    #- name: NuGet Pack
    #  run: nuget pack build/JonLipsky.Microsoft.Maui.Graphics.Xaml.UWP.nuspec -Version 0.1.${{ github.run_number }} -OutputDirectory . -BasePath .

    #- name: NuGet Pack
    #  run: nuget pack build/JonLipsky.Microsoft.Maui.Graphics.Xaml.WPF.nuspec -Version 0.1.${{ github.run_number }} -OutputDirectory . -BasePath .

    #- name: 'Upload Artifacts'
    #  uses: actions/upload-artifact@v2
    #  with:
    #    name: windows-artifacts
    #    path: "*.nupkg"

  build-on-mac:
    runs-on: macos-latest
    steps:

    - name: Checkout source code
      uses: actions/checkout@v2
              
    - name: Install NuGet
      uses: nuget/setup-nuget@v1
      with:
        nuget-version: '5.x'

    - name: Install DotNet Preview
      shell: bash
      run: >
        export PATH="/usr/local/share/dotnet/:~/.dotnet/tools:$PATH" &&
        curl -L https://raw.githubusercontent.com/dotnet/install-scripts/7a9d5dcab92cf131fc2d8977052f8c2c2d540e22/src/dotnet-install.sh > dotnet-install.sh &&
        sh dotnet-install.sh --version $DotNetVersion --install-dir $DOTNET_ROOT --verbose &&
        dotnet --list-sdks &&
        dotnet tool install --global boots --add-source "https://api.nuget.org/v3/index.json"
        boots $AndroidPkg
        boots $iOSPkg
        boots $MacCatalystPkg

    - name: Update project version
      uses: roryprimrose/set-vs-sdk-project-version@v1
      with:
        projectFilter: 'src/*/*.csproj'
        version: '0.1.${{ github.run_number }}'

    - name: NuGet Restore
      run: |
        nuget restore build/Build.Microsoft.Maui.Graphics.Mac.sln
        dotnet restore build/Build.Microsoft.Maui.Graphics-net6.sln
    
    - name: Build
      run: |
        msbuild build/Build.Microsoft.Maui.Graphics.Mac.sln /verbosity:normal /r /t:Rebuild /p:Configuration=Release
        dotnet build build/Build.Microsoft.Maui.Graphics-net6.sln -p:Configuration=Release           

    #- name: Build
    #  run: msbuild build/Build.Microsoft.Maui.Graphics.Mac.sln /verbosity:normal /t:Rebuild /p:Configuration=Release
    
    - name: NuGet Pack
      run: |
        nuget pack build/Microsoft.Maui.Graphics.nuspec -Version 0.1.${{ github.run_number }} -OutputDirectory . -BasePath .
        nuget pack build/Microsoft.Maui.Graphics.Text.Markdig.nuspec -Version 0.1.${{ github.run_number }} -OutputDirectory . -BasePath .

    #- name: NuGet Pack
    #  run: nuget pack build/JonLipsky.Microsoft.Maui.Graphics.Skia.nuspec -Version 0.1.${{ github.run_number }} -OutputDirectory . -BasePath .

    #- name: NuGet Pack
    #  run: nuget pack build/JonLipsky.Microsoft.Maui.Graphics.Forms.nuspec -Version 0.1.${{ github.run_number }} -OutputDirectory . -BasePath .

    #- name: NuGet Pack
    #  run: nuget pack build/JonLipsky.Microsoft.Maui.Graphics.Skia.Forms.nuspec -Version 0.1.${{ github.run_number }} -OutputDirectory . -BasePath .

    #- name: NuGet Pack
    #  run: nuget pack build/Microsoft.Maui.Graphics.Text.Markdig.nuspec -Version 0.1.${{ github.run_number }} -OutputDirectory . -BasePath .

    - name: 'Upload Artifacts'
      uses: actions/upload-artifact@v2
      with:
        name: mac-artifacts
        path: "*.nupkg"

  release:
    needs: [build-on-mac, build-on-windows]
    runs-on: ubuntu-latest
    steps:

    - name: Download Mac Artifacts
      uses: actions/download-artifact@v2
      with:
        name: mac-artifacts

    - name: Download Windows Artifacts
      uses: actions/download-artifact@v2
      with:
        name: windows-artifacts
    
    - name: Install GPR
      run: dotnet tool install -g gpr --no-cache -v q
      
    - name: Publish package to GitHub registry
      run: gpr push *.nupkg --api-key ${{ secrets.PACKAGES_TOKEN }}   
      working-directory: .    

    - name: Publish package to NuGet
      run: dotnet nuget push "*.nupkg" --api-key ${{secrets.NUGET_API_KEY}} --skip-duplicate --source https://api.nuget.org/v3/index.json
      working-directory: . 


